const products = [
    {
      id: 1,
      name: 'Bicicleta de Montaña',
      price: 499.99,
      image: 'https://media.revistagq.com/photos/63a07ebbcd47ea011bd7747f/16:9/w_2560%2Cc_limit/2023-Trek-Fuel-EXe-XX1-AXS-Pack-Shots-01236.jpg',
      features: ['Suspensión Delantera', 'Frenos de Disco', '21 Velocidades'],
      details: {
        betweenLugs: '15 mm',
        bracelet: 'Aluminio',
        case: 'Carbono',
        caseDiameter: '29 pulgadas',
        dialColor: 'Negro',
        crystal: 'Cristal Templado',
        waterResistance: '3 bar (30 metros / 100 pies)',
      },
    },
    {
      id: 2,
      name: 'Bicicleta de Carretera',
      price: 699.99,
      image: 'https://www.cmdsport.com/app/uploads/2022/06/bicicleta-de-carretera-scott-foil-rc-bis.jpg',
      features: ['Marco de Fibra de Carbono', 'Frenos de Disco Hidráulicos', '22 Velocidades'],
      details: {
        betweenLugs: '20 mm',
        bracelet: 'Fibra de Carbono',
        case: 'Aluminio',
        caseDiameter: '28 pulgadas',
        dialColor: 'Rojo',
        crystal: 'Cristal Templado',
        waterResistance: '2 bar (20 metros / 66 pies)',
      },
    },
    {
      id: 3,
      name: 'Casco de Ciclista',
      price: 49.99,
      image: 'https://ciclosfera.com/img/bdea24253ae82d823219b54c3826a0f3.872.0.0.0.b9026042.webp',
      features: ['Visera Desmontable', 'Ajuste de Tamaño', 'Ventilación Óptima'],
      details: {
        betweenLugs: 'N/A',
        bracelet: 'N/A',
        case: 'Policarbonato',
        caseDiameter: 'Talla Única',
        dialColor: 'Negro y Rojo',
        crystal: 'N/A',
        waterResistance: 'N/A',
      },
    },
    {
      id: 4,
      name: 'Guantes de Ciclismo',
      price: 19.99,
      image: 'https://i5.walmartimages.com.mx/mg/gm/3pp/asr/08a21ffc-76a9-4c96-9877-7b935b5833b8.d58a80df5dd50442587d811e5352c226.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF',
      features: ['Antideslizante', 'Transpirables', 'Protección Adicional'],
      details: {
        betweenLugs: 'N/A',
        bracelet: 'N/A',
        case: 'Tela y Caucho',
        caseDiameter: 'Talla Única',
        dialColor: 'Negro y Verde',
        crystal: 'N/A',
        waterResistance: 'N/A',
      },
    },
    {
      id: 5,
      name: 'Luz Delantera Bicicleta',
      price: 29.99,
      image: 'https://www.ebest.cl/media/catalog/product/cache/47abc4af9d81a631bd44d97ba9797770/l/u/luz-delantera-para-bicicleta-magicshine-allty-600_1_.jpg',
      features: ['LED Alta Potencia', 'Recargable USB', 'Resistente al Agua'],
      details: {
        betweenLugs: 'N/A',
        bracelet: 'N/A',
        case: 'Plástico',
        caseDiameter: 'N/A',
        dialColor: 'Negro',
        crystal: 'N/A',
        waterResistance: '5 bar (50 metros / 167 pies)',
      },
    },
    {
      id: 6,
      name: 'Portabicicletas para Auto',
      price: 99.99,
      image: 'https://static2.elcontainer.cl/3766-thickbox_default/porta-bicicleta-para-autos.jpg',
      features: ['Capacidad para 3 Bicicletas', 'Fácil Instalación', 'Seguro y Resistente'],
      details: {
        betweenLugs: 'N/A',
        bracelet: 'N/A',
        case: 'Acero y Plástico',
        caseDiameter: 'N/A',
        dialColor: 'Negro',
        crystal: 'N/A',
        waterResistance: 'N/A',
      },
    },
    {
      id: 7,
      name: 'Kit de Herramientas para Bicicleta',
      price: 39.99,
      image: 'https://http2.mlstatic.com/D_NQ_NP_656545-MLC45256436125_032021-O.webp',
      features: ['Compacto', 'Multifuncional', 'Incluye Bolsa de Transporte'],
      details: {
        betweenLugs: 'N/A',
        bracelet: 'N/A',
        case: 'Acero y Plástico',
        caseDiameter: 'N/A',
        dialColor: 'Negro y Rojo',
        crystal: 'N/A',
        waterResistance: 'N/A',
      },
    },
  ];

export default products;